routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {   
    
    return view('welcome'); });



Auth::routes(); 
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/cpanal', 'cpanal@index')->name('cpanal');
Route::get('post','Post@index');
Route::get('post/{id}','Post@update');

Route::get('coustomer','coustomer@mylist')->name('mylist');


Route::resource('posts','PostsController');
Route::resource('coustomer','CoustomerController');
Route::resource('password','PasswordController');
Route::resource('payment','PaymentController');

app/coustomer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class coustomer extends Model
{
    //
}

app/Http/Controllers/CoustomerController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use\App\coustomer;
use\DB;


class CoustomerController extends Controller
{  
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    




    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

       

        $users = coustomer::orderBy('id', 'DESC')->paginate(2);
        return view('coustomer.index')->with('users',$users);
        
        
    }

  


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('coustomer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request,[
            'name' => 'required|max:255',
            'amount' => 'required|max:6',
            'component' => 'required|max:6',
            'phone' => 'required|max:10'
        ]);

        $newuser = new coustomer;
            $newuser->name  =  ucfirst($request->input('name'));
            $newuser->phone = $request->input('phone');
            $newuser->amount= $request->input('amount');
            $newuser->component_amount = $request->input('component');
           
           
            if($newuser->save()){
               return redirect("coustomer");
            }else{}
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $coustomer = coustomer::find($id);
        return view('coustomer.show')->with('user',$coustomer);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $coustomer = coustomer::find($id);
        return view('coustomer.edit')->with('coustomer',$coustomer);

     
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       
               $this->validate($request,[
            'name' => 'required|max:255',
            'amount' => 'required|max:6',
            'component' => 'required|max:6',
            'phone' => 'required|max:10'
        ]);

        $edited_customer = coustomer::find($id);
            $edited_customer->name  =  ucfirst($request->input('name'));
            $edited_customer->phone = $request->input('phone');
            $edited_customer->amount= $request->input('amount');
            $edited_customer->component_amount = $request->input('component');
           
           
            if($edited_customer->save()){
               return redirect("coustomer");
            }else{}
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
   
    return('I will delete..');
    }
}

resources/views/coustomer/create.blade.php
@extends('layouts.app')
@section('content')


<div class="container col-12 col-md-auto">
        
        <div class="row justify-content-center mt-4 pt-4 mb-4 pb-4">
         


            <!-- Material form subscription -->
<div class="card">

       
    
        <!--Card content-->
        <div class="card-body px-lg-5">
    
            <!-- Form -->
            <form method="POST" action="/coustomer/"  class="text-center" style="color: #757575;"> 
             
    
                <p>Enter the name or phone number of the customer.</p>
    
                <p>
                    <a href="" target="_blank">Find a customer</a>
                </p>
    
                <!-- Name -->
                <div class="md-form mt-3">
                    <input type="text" name="name" id="name" class="form-control">
                    <label for="name">Name</label>
                </div>
    




                     
         
               
                        <div class="md-form">
                        <input type="number" name="amount"  id="number" class="form-control">
                        <label for="amount">Amount</label>
                        </div>
                        <div class="md-form">
                        <input type="number" name="component"  id="component" class="form-control">
                        <label for="component">Component</label>
                        </div>
                 



                
              
                <div class="md-form">
                    <input type="number" id="phone" name="phone" class="form-control">
                    <label for="phone">Phone</label>
                </div>
    
                <!-- Sign in button -->
                <button class="btn btn-info  waves-effect" type="submit">Save</button>
                @csrf
            </form>
            <!-- Form -->
    
        </div>
    
    </div>
    <!-- Material form subscription -->
       
   </div>
 </div>


@endsection
@section('js')
    <script type="text/javascript">
       //alert("Testng");
    </script>
@endsection

resources/views/coustomer/edit.blade.php
@extends('layouts.app')
@section('content')



<div class="container col-12 col-md-auto">
        
        <div class="row justify-content-center mt-4 pt-4 mb-4 pb-4">
         


            <!-- Material form subscription -->
<div class="card">

       
    
        <!--Card content-->
        <div class="card-body px-lg-5">
    
            <!-- Form -->
         
                <form method="post" action="{{ route('coustomer.update',$coustomer->id) }}">
                      
                        @method('PUT')

                        
                <p>Enter the name or phone number of the customer.</p>
    
                <p>
                    <a href="" target="_blank">Find a customer</a>
                </p>
    
                <!-- Name -->
                <div class="md-form mt-3">
                <input type="text" name="name" id="name" class="form-control" value="{{$coustomer->name}}">
                    <label for="name">Name</label>
                </div>
    




                     
         
               
                        <div class="md-form">
                        <input type="number" name="amount"  id="number" class="form-control" value="{{$coustomer->amount}}">
                        <label for="amount">Amount</label>
                        </div>
                        <div class="md-form">
                        <input type="number" name="component"  id="component" class="form-control" value="{{$coustomer->component_amount}}">
                        <label for="component">Component</label>
                        </div>
                 



                
              
                <div class="md-form">
                    <input type="number" id="phone" name="phone" class="form-control" value="{{$coustomer->phone}}">
                    <label for="phone">Phone</label>
                </div>
    
                <!-- Sign in button -->
                <button class="btn btn-info  waves-effect" type="submit">Save</button>
                @csrf
            </form>
            <!-- Form -->
    
        </div>
    
    </div>
    <!-- Material form subscription -->
       
   </div>
 </div>


@endsection
@section('js')
    <script type="text/javascript">
       //alert("Testng");
    </script>
@endsection

resources/views/coustomer/index.blade.php
@extends('layouts.app')
@section('content')

<style>
.dlt-btn{

  margin: 0px;
  padding: 1px 5px 0px 5px ;
  border-radius: 10px;
}
</style>

<div class="container">

        <nav class="navbar navbar-expand-lg navbar-light blue-grey lighten-5 ">

                <!-- Navbar brand -->
               <h5>
                   Coustomers
               </h5>
          
                <!-- Collapse button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          
                <!-- Collapsible content -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
          
                  <!-- Links -->
                  <ul class="navbar-nav mr-auto">
                   
          
                  </ul>
                  <!-- Links -->
          
                  <!-- Search form -->
                  <form class="form-inline">
                        <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                  
                                    <button class="btn btn-primary btn-md m-0 px-3 py-2 z-depth-0 dropdown-toggle" type="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Search With</button>
                                 
                                    <div class="dropdown-menu">
                                    <a class="dropdown-item" href="#">Name</a>
                                    <a class="dropdown-item" href="#">Phone</a>
                                </div>

                              

                                <input type="text" class="form-control" aria-label="Text input with dropdown button">

                                


                              </div>
                        </div>
                            
                  </form>
                </div>
                <!-- Collapsible content -->
          
              </nav>



@if(count($users)>0)
                




        <table class="table table-hover table-dark">
                <thead>
                  <tr>
                   
                    <th scope="col">ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Phone</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Component</th>
                    <th scope="col">Date of Issue</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>

                
                   
                  
                     
                     

                  @foreach ($users as $user)
                  <tr>
                      <th scope="row">{{$user->id}}</th>
                      <td>{{$user->name}}</td>
                      <td>{{$user->phone}}</td>
                      <td>{{$user->amount}}</td>
                      <td>{{$user->component_amount}}</td>
                      <td>{{$user->updated_at}}</td>
                      <td>
                      <a href="/coustomer/{{$user->id}}/edit" type="button" class="btn  btn-primary waves-effect waves-light dlt-btn">
                            <i class="fas fa-pencil-alt"></i>
                        </a>
                      </td>


                      <td>
                        

                         
                      <a href="/coustomer/{{$user->id}}" type="button" class="btn  btn-primary waves-effect waves-light dlt-btn">
                            Show
                        </a>
                         
                      
                        
                            <button  type="submit" name="dlt[]" value="{{$user->id}}" class="btn  btn-danger waves-effect waves-light dlt-btn">
                                D<i class="far fa-trash-alt"></i>
                            </button>

                        </td>




                    </tr>
                  @endforeach

               
                
                
                  @else
                  <hr class="card"> <h2>No user found...</h2>
                  @endif
               
              


                
                </tbody>
              </table>
             





              <nav aria-label="Page navigation example">
          <ul class="pagination pagination-circle pg-blue justify-content-center">
           
         
            {{$users->links()}}

          
          </ul>
        </nav>

</div>

@endsection
@section('js')
    <script type="text/javascript">
       //alert("Testng");
    </script>
@endsection

resources/views/coustomer/show.blade.php
@extends('layouts.app')
@section('content')

<style>
.dlt-btn{

  margin: 0px;
  padding: 1px 5px 0px 5px ;
  border-radius: 10px;
}
</style>

<div class="container-fluid">
<div class="container card pt-4 mt-4 pb-4 mt-4">

        




<table class="table table-hover table-dark">
                <thead>
                  <tr>
                   
                    <th scope="col">ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Phone</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Component</th>
                    <th scope="col">Date of Issue</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>

                
                   
                  
                     
                     

               
                  <tr>
                      <th scope="row">{{$user->id}}</th>
                      <td>{{$user->name}}</td>
                      <td>{{$user->phone}}</td>
                      <td>{{$user->amount}}</td>
                      <td>{{$user->component_amount}}</td>
                      <td>{{$user->updated_at}}</td>
                      <td>
                    
                      </td>


                      <td>
                        

                         
                            
                         
                      
                        
                            <button  type="submit" name="dlt[]" value="{{$user->id}}" class="btn  btn-danger waves-effect waves-light dlt-btn">
                                Delete<i class="far fa-trash-alt"></i>
                            </button>

                        </td>




                    </tr>
             
          
              


                
                </tbody>
              </table>
             

             
</div>
</div>

@endsection
@section('js')
    <script type="text/javascript">
       //alert("Testng");
    </script>
@endsection